"""Added missingapplication columns

Revision ID: 1bfb594fe9d8
Revises: 7f54f284eb95
Create Date: 2026-06-22 19:37:46.518278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfb594fe9d8'
down_revision: Union[str, Sequence[str], None] = '7f54f284eb95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('interview_type', sa.Enum('PHONE', 'VIDEO', 'TECHNICAL', 'HR', 'FINAL', name='interviewtype'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.add_column('applications', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('applications', sa.Column('job_url', sa.String(length=500), nullable=True))
    op.add_column('applications', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('applications', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('applications', sa.Column('deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('applications', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('companies', sa.Column('company_name', sa.String(length=255), nullable=False))
    op.add_column('companies', sa.Column('location', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=True)
    op.drop_column('companies', 'name')
    op.drop_constraint(op.f('users_password_hash_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_password_hash_key'), 'users', ['password_hash'], postgresql_nulls_not_distinct=False)
    op.add_column('companies', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.drop_column('companies', 'location')
    op.drop_column('companies', 'company_name')
    op.alter_column('applications', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('applications', 'follow_up_date')
    op.drop_column('applications', 'deadline')
    op.drop_column('applications', 'updated_at')
    op.drop_column('applications', 'created_at')
    op.drop_column('applications', 'job_url')
    op.drop_column('applications', 'location')
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_table('interviews')
    # ### end Alembic commands ###
