"""just fixed the typo for database models

Revision ID: 412ef019ec8f
Revises: bd237623e716
Create Date: 2026-06-26 00:27:07.376336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412ef019ec8f'
down_revision: Union[str, Sequence[str], None] = 'bd237623e716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    interview_type_enum = sa.Enum(
       "online",
       "phone",
       "onsite",
       "technical",
       "hr",
       name="interviewtype"
    )
    interview_type_enum.create(op.get_bind(), checkfirst=True)
    
    interview_status_enum = sa.Enum(
        "scheduled",
        "completed",
        "cancelled",
        name="interviewstatus"
    )
    interview_status_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column("interviews", sa.Column("interview_type", interview_type_enum, nullable=False, server_default="online"))
    op.add_column("interviews", sa.Column("status", interview_status_enum, nullable=False, server_default="scheduled"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'status')
    op.drop_column('interviews', 'interview_type')
    
    interview_type_enum = sa.Enum(
       "online",
       "phone",
       "onsite",
       "technical",
       "hr",
       name="interviewtype"
    )
    
    interview_status_enum = sa.Enum(
        "scheduled",
        "completed",
        "cancelled",
        name="interviewstatus"
    )
    
    interview_status_enum.drop(op.get_bind(), checkfirst=True)
    interview_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
