"""Updated interview model

Revision ID: 69f4db873957
Revises: abc358380e76
Create Date: 2026-06-24 21:51:14.102821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f4db873957'
down_revision: Union[str, Sequence[str], None] = 'abc358380e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('interviews', sa.Column('interview_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('interviews', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'updated_at')
    op.drop_column('interviews', 'interview_date')
    op.drop_column('interviews', 'title')
    # ### end Alembic commands ###
