"""initialized tables

Revision ID: bd237623e716
Revises: 1386f00c0981
Create Date: 2026-06-25 23:40:57.233021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd237623e716'
down_revision: Union[str, Sequence[str], None] = '1386f00c0981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    interviewstatus = sa.Enum(
       "SCHEDULED",
       "COMPLETED",
       "CANCELLED",
       name="interviewstatus"
    )
    
    interviewstatus.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "interviews",
        sa.Column(
            "status",
            interviewstatus,
            nullable=False,
            server_default="SCHEDULED"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'status')
    
    interviewstatus = sa.Enum(
        "SCHEDULED",
        "COMPLETED",
        "CANCELLED",
        name="interviewstatus"
    )
    
    interviewstatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
